### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by YenBenGrey** [roth-michael/region-attacher#4]
Hello Michael, 

Love this module. 

This is a feature request, bit of a pipe dream but it looks like Limits isn't making any movement, is there a way that you and your mighty dev powers recreate something similar just for region attacher? 

Totally no worries if not, this is a fools hope/request.

**Comment by roth-michael** [comment]
Hey YenBen. Sorry to say, but that'd definitely be out of scope for Region Attacher. And even if it weren't, I’m sure it'd take me longer to get something polished done than it'll take Eber to come out with limits for v12. Fingers crossed it's soon for ya.
